# Generated by Django 5.1.4 on 2024-12-11 23:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("webapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="contactgroup",
            name="color",
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
