# Generated by Django 5.1.4 on 2024-12-12 08:09

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("webapp", "0002_contactgroup_color"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="contactgroup",
            options={"ordering": ["-updated_at"]},
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DELIVERED", "Delivered"),
                            ("FAILED", "Failed"),
                            ("RECEIVED", "Received"),
                        ],
                        default="DELIVERED",
                        max_length=10,
                    ),
                ),
                (
                    "message",
                    models.TextField(
                        validators=[django.core.validators.MaxLengthValidator(160)]
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "contact",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="webapp.contact",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
        migrations.DeleteModel(
            name="CampaignMetrics",
        ),
    ]
