# Generated by Django 5.1.4 on 2024-12-13 02:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("webapp", "0004_alter_campaign_created_by"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="campaign",
            name="group",
        ),
        migrations.AddField(
            model_name="campaign",
            name="groups",
            field=models.ManyToManyField(
                blank=True, related_name="campaigns", to="webapp.contactgroup"
            ),
        ),
    ]
